name: NodeSchool Augusta
description: Augusta, Ga Chapter of NodeSchool
url: "http://nodeschool.io/augusta"

permalink: /:title/

collections:
  contributors:
    output: true
    permalink: /contributors/:path/
  events:
    output: true
    permalink: /events/:path/
  projects:
    output: true
    permalink: /projects/:path/

version: v0.1.0

exclude:
  - README.md